"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppTheoryFunction = exports.AppTheoryLambdaTrafficShiftType = void 0;
const JSII_RTTI_SYMBOL_1 = Symbol.for("jsii.rtti");
const aws_cdk_lib_1 = require("aws-cdk-lib");
const codedeploy = require("aws-cdk-lib/aws-codedeploy");
const iam = require("aws-cdk-lib/aws-iam");
const lambda = require("aws-cdk-lib/aws-lambda");
const logs = require("aws-cdk-lib/aws-logs");
const constructs_1 = require("constructs");
/**
 * Traffic shifting mode for AppTheory-managed Lambda aliases.
 */
var AppTheoryLambdaTrafficShiftType;
(function (AppTheoryLambdaTrafficShiftType) {
    /**
     * Shift all traffic to the new version at once.
     */
    AppTheoryLambdaTrafficShiftType["ALL_AT_ONCE"] = "ALL_AT_ONCE";
    /**
     * Shift one canary increment, wait, then shift the remaining traffic.
     */
    AppTheoryLambdaTrafficShiftType["CANARY"] = "CANARY";
    /**
     * Shift traffic in equal linear increments.
     */
    AppTheoryLambdaTrafficShiftType["LINEAR"] = "LINEAR";
})(AppTheoryLambdaTrafficShiftType || (exports.AppTheoryLambdaTrafficShiftType = AppTheoryLambdaTrafficShiftType = {}));
class AppTheoryFunction extends constructs_1.Construct {
    constructor(scope, id, props) {
        super(scope, id);
        const { alias, roleName, ...inputLambdaProps } = props;
        const lambdaProps = { ...inputLambdaProps };
        if (roleName !== undefined) {
            if (lambdaProps.role) {
                throw new Error("AppTheoryFunction cannot honor props.roleName when props.role supplies the execution role; omit props.role or configure its name where that role is created");
            }
        }
        const logRetention = lambdaProps.logRetention ?? logs.RetentionDays.ONE_MONTH;
        const logRemovalPolicy = lambdaProps.logRemovalPolicy;
        delete lambdaProps.logRetention;
        delete lambdaProps.logRemovalPolicy;
        delete lambdaProps.logRetentionRetryOptions;
        delete lambdaProps.logRetentionRole;
        let boundLogGroup = lambdaProps.logGroup;
        if (!boundLogGroup && lambdaProps.functionName) {
            boundLogGroup = new logs.LogGroup(this, "LogGroup", {
                logGroupName: `/aws/lambda/${lambdaProps.functionName}`,
                retention: logRetention,
                removalPolicy: logRemovalPolicy,
            });
        }
        this.fn = new lambda.Function(this, "Function", {
            ...lambdaProps,
            logGroup: boundLogGroup,
            architecture: lambdaProps.architecture ?? lambda.Architecture.ARM_64,
            tracing: lambdaProps.tracing ?? lambda.Tracing.ACTIVE,
            memorySize: lambdaProps.memorySize ?? 256,
            timeout: lambdaProps.timeout ?? aws_cdk_lib_1.Duration.seconds(10),
        });
        if (roleName !== undefined) {
            if (!roleName.trim()) {
                throw new Error("AppTheoryFunction roleName must not be empty");
            }
            if (roleName.length > 64) {
                throw new Error("AppTheoryFunction roleName must not exceed 64 characters");
            }
            if (!/^[\w+=,.@-]+$/.test(roleName)) {
                throw new Error("AppTheoryFunction roleName must match [\\w+=,.@-]+");
            }
            const roleResource = this.fn.role?.node.defaultChild;
            if (!(roleResource instanceof iam.CfnRole)) {
                throw new Error(`AppTheoryFunction cannot apply the required stable roleName ${JSON.stringify(roleName)} because the Lambda execution role's default child is not an AWS::IAM::Role`);
            }
            roleResource.addPropertyOverride("RoleName", roleName);
        }
        if (boundLogGroup) {
            this.logGroup = boundLogGroup;
        }
        else {
            // Anonymous Lambda physical names are generated by CloudFormation. Keep
            // the finite-retention log group, but require callers that need a
            // fail-safe existing-stack upgrade/adoption path to pass logGroup or a
            // concrete functionName so the Lambda L2 can bind the group up front.
            const logGroup = new logs.LogGroup(this, "LogGroup", {
                logGroupName: `/aws/lambda/${this.fn.functionName}`,
                retention: logRetention,
                removalPolicy: logRemovalPolicy,
            });
            this.logGroup = logGroup;
        }
        if (alias) {
            this.configureAlias(alias);
        }
    }
    configureAlias(options) {
        const aliasName = String(options.name ?? "live").trim();
        if (!aliasName) {
            throw new Error("AppTheoryFunction alias.name must not be empty");
        }
        const alias = new lambda.Alias(this, "Alias", {
            aliasName,
            version: this.fn.currentVersion,
            description: options.description,
            provisionedConcurrentExecutions: options.provisionedConcurrentExecutions,
        });
        this.alias = alias;
        if (options.deployment) {
            const deploymentGroup = new codedeploy.LambdaDeploymentGroup(this, "DeploymentGroup", {
                alias,
                deploymentConfig: deploymentConfigFor(this, options.deployment),
                alarms: options.deployment.alarms,
                preHook: options.deployment.preHook,
                postHook: options.deployment.postHook,
                autoRollback: options.deployment.autoRollback,
            });
            this.deploymentGroup = deploymentGroup;
        }
    }
}
exports.AppTheoryFunction = AppTheoryFunction;
_a = JSII_RTTI_SYMBOL_1;
AppTheoryFunction[_a] = { fqn: "@theory-cloud/apptheory-cdk.AppTheoryFunction", version: "3.0.2" };
function deploymentConfigFor(scope, options) {
    const type = options.trafficShiftType ?? AppTheoryLambdaTrafficShiftType.CANARY;
    switch (type) {
        case AppTheoryLambdaTrafficShiftType.ALL_AT_ONCE:
            return codedeploy.LambdaDeploymentConfig.ALL_AT_ONCE;
        case AppTheoryLambdaTrafficShiftType.LINEAR:
            return new codedeploy.LambdaDeploymentConfig(scope, "LinearDeploymentConfig", {
                trafficRouting: codedeploy.TrafficRouting.timeBasedLinear({
                    percentage: normalizedPercentage(options.percentage),
                    interval: options.interval ?? aws_cdk_lib_1.Duration.minutes(1),
                }),
            });
        case AppTheoryLambdaTrafficShiftType.CANARY:
            return new codedeploy.LambdaDeploymentConfig(scope, "CanaryDeploymentConfig", {
                trafficRouting: codedeploy.TrafficRouting.timeBasedCanary({
                    percentage: normalizedPercentage(options.percentage),
                    interval: options.interval ?? aws_cdk_lib_1.Duration.minutes(5),
                }),
            });
        default:
            throw new Error(`AppTheoryFunction unsupported deployment type: ${String(type)}`);
    }
}
function normalizedPercentage(input) {
    const value = input ?? 10;
    if (!Number.isFinite(value) || value <= 0 || value >= 100) {
        throw new Error("AppTheoryFunction deployment percentage must be greater than 0 and less than 100");
    }
    return value;
}
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZnVuY3Rpb24uanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJmdW5jdGlvbi50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7OztBQUFBLDZDQUF1QztBQUV2Qyx5REFBeUQ7QUFDekQsMkNBQTJDO0FBQzNDLGlEQUFpRDtBQUNqRCw2Q0FBNkM7QUFDN0MsMkNBQXVDO0FBRXZDOztHQUVHO0FBQ0gsSUFBWSwrQkFlWDtBQWZELFdBQVksK0JBQStCO0lBQ3pDOztPQUVHO0lBQ0gsOERBQTJCLENBQUE7SUFFM0I7O09BRUc7SUFDSCxvREFBaUIsQ0FBQTtJQUVqQjs7T0FFRztJQUNILG9EQUFpQixDQUFBO0FBQ25CLENBQUMsRUFmVywrQkFBK0IsK0NBQS9CLCtCQUErQixRQWUxQztBQXNHRCxNQUFhLGlCQUFrQixTQUFRLHNCQUFTO0lBTTlDLFlBQVksS0FBZ0IsRUFBRSxFQUFVLEVBQUUsS0FBNkI7UUFDckUsS0FBSyxDQUFDLEtBQUssRUFBRSxFQUFFLENBQUMsQ0FBQztRQUVqQixNQUFNLEVBQUUsS0FBSyxFQUFFLFFBQVEsRUFBRSxHQUFHLGdCQUFnQixFQUFFLEdBQUcsS0FBSyxDQUFDO1FBQ3ZELE1BQU0sV0FBVyxHQUF5QixFQUFFLEdBQUcsZ0JBQWdCLEVBQUUsQ0FBQztRQUNsRSxJQUFJLFFBQVEsS0FBSyxTQUFTLEVBQUUsQ0FBQztZQUMzQixJQUFJLFdBQVcsQ0FBQyxJQUFJLEVBQUUsQ0FBQztnQkFDckIsTUFBTSxJQUFJLEtBQUssQ0FDYiw2SkFBNkosQ0FDOUosQ0FBQztZQUNKLENBQUM7UUFDSCxDQUFDO1FBQ0QsTUFBTSxZQUFZLEdBQUcsV0FBVyxDQUFDLFlBQVksSUFBSSxJQUFJLENBQUMsYUFBYSxDQUFDLFNBQVMsQ0FBQztRQUM5RSxNQUFNLGdCQUFnQixHQUFHLFdBQVcsQ0FBQyxnQkFBZ0IsQ0FBQztRQUN0RCxPQUFRLFdBQXFELENBQUMsWUFBWSxDQUFDO1FBQzNFLE9BQVEsV0FBOEMsQ0FBQyxnQkFBZ0IsQ0FBQztRQUN4RSxPQUFRLFdBQXNELENBQUMsd0JBQXdCLENBQUM7UUFDeEYsT0FBUSxXQUE4QyxDQUFDLGdCQUFnQixDQUFDO1FBRXhFLElBQUksYUFBYSxHQUFHLFdBQVcsQ0FBQyxRQUFRLENBQUM7UUFDekMsSUFBSSxDQUFDLGFBQWEsSUFBSSxXQUFXLENBQUMsWUFBWSxFQUFFLENBQUM7WUFDL0MsYUFBYSxHQUFHLElBQUksSUFBSSxDQUFDLFFBQVEsQ0FBQyxJQUFJLEVBQUUsVUFBVSxFQUFFO2dCQUNsRCxZQUFZLEVBQUUsZUFBZSxXQUFXLENBQUMsWUFBWSxFQUFFO2dCQUN2RCxTQUFTLEVBQUUsWUFBWTtnQkFDdkIsYUFBYSxFQUFFLGdCQUFnQjthQUNoQyxDQUFDLENBQUM7UUFDTCxDQUFDO1FBRUQsSUFBSSxDQUFDLEVBQUUsR0FBRyxJQUFJLE1BQU0sQ0FBQyxRQUFRLENBQUMsSUFBSSxFQUFFLFVBQVUsRUFBRTtZQUM5QyxHQUFHLFdBQVc7WUFDZCxRQUFRLEVBQUUsYUFBYTtZQUN2QixZQUFZLEVBQUUsV0FBVyxDQUFDLFlBQVksSUFBSSxNQUFNLENBQUMsWUFBWSxDQUFDLE1BQU07WUFDcEUsT0FBTyxFQUFFLFdBQVcsQ0FBQyxPQUFPLElBQUksTUFBTSxDQUFDLE9BQU8sQ0FBQyxNQUFNO1lBQ3JELFVBQVUsRUFBRSxXQUFXLENBQUMsVUFBVSxJQUFJLEdBQUc7WUFDekMsT0FBTyxFQUFFLFdBQVcsQ0FBQyxPQUFPLElBQUksc0JBQVEsQ0FBQyxPQUFPLENBQUMsRUFBRSxDQUFDO1NBQ3JELENBQUMsQ0FBQztRQUVILElBQUksUUFBUSxLQUFLLFNBQVMsRUFBRSxDQUFDO1lBQzNCLElBQUksQ0FBQyxRQUFRLENBQUMsSUFBSSxFQUFFLEVBQUUsQ0FBQztnQkFDckIsTUFBTSxJQUFJLEtBQUssQ0FBQyw4Q0FBOEMsQ0FBQyxDQUFDO1lBQ2xFLENBQUM7WUFDRCxJQUFJLFFBQVEsQ0FBQyxNQUFNLEdBQUcsRUFBRSxFQUFFLENBQUM7Z0JBQ3pCLE1BQU0sSUFBSSxLQUFLLENBQUMsMERBQTBELENBQUMsQ0FBQztZQUM5RSxDQUFDO1lBQ0QsSUFBSSxDQUFDLGVBQWUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLEVBQUUsQ0FBQztnQkFDcEMsTUFBTSxJQUFJLEtBQUssQ0FBQyxvREFBb0QsQ0FBQyxDQUFDO1lBQ3hFLENBQUM7WUFDRCxNQUFNLFlBQVksR0FBRyxJQUFJLENBQUMsRUFBRSxDQUFDLElBQUksRUFBRSxJQUFJLENBQUMsWUFBWSxDQUFDO1lBQ3JELElBQUksQ0FBQyxDQUFDLFlBQVksWUFBWSxHQUFHLENBQUMsT0FBTyxDQUFDLEVBQUUsQ0FBQztnQkFDM0MsTUFBTSxJQUFJLEtBQUssQ0FDYiwrREFBK0QsSUFBSSxDQUFDLFNBQVMsQ0FBQyxRQUFRLENBQUMsNkVBQTZFLENBQ3JLLENBQUM7WUFDSixDQUFDO1lBQ0QsWUFBWSxDQUFDLG1CQUFtQixDQUFDLFVBQVUsRUFBRSxRQUFRLENBQUMsQ0FBQztRQUN6RCxDQUFDO1FBRUQsSUFBSSxhQUFhLEVBQUUsQ0FBQztZQUNqQixJQUF5QyxDQUFDLFFBQVEsR0FBRyxhQUFhLENBQUM7UUFDdEUsQ0FBQzthQUFNLENBQUM7WUFDTix3RUFBd0U7WUFDeEUsa0VBQWtFO1lBQ2xFLHVFQUF1RTtZQUN2RSxzRUFBc0U7WUFDdEUsTUFBTSxRQUFRLEdBQUcsSUFBSSxJQUFJLENBQUMsUUFBUSxDQUFDLElBQUksRUFBRSxVQUFVLEVBQUU7Z0JBQ25ELFlBQVksRUFBRSxlQUFlLElBQUksQ0FBQyxFQUFFLENBQUMsWUFBWSxFQUFFO2dCQUNuRCxTQUFTLEVBQUUsWUFBWTtnQkFDdkIsYUFBYSxFQUFFLGdCQUFnQjthQUNoQyxDQUFDLENBQUM7WUFDRixJQUF5QyxDQUFDLFFBQVEsR0FBRyxRQUFRLENBQUM7UUFDakUsQ0FBQztRQUVELElBQUksS0FBSyxFQUFFLENBQUM7WUFDVixJQUFJLENBQUMsY0FBYyxDQUFDLEtBQUssQ0FBQyxDQUFDO1FBQzdCLENBQUM7SUFDSCxDQUFDO0lBRU8sY0FBYyxDQUFDLE9BQXNDO1FBQzNELE1BQU0sU0FBUyxHQUFHLE1BQU0sQ0FBQyxPQUFPLENBQUMsSUFBSSxJQUFJLE1BQU0sQ0FBQyxDQUFDLElBQUksRUFBRSxDQUFDO1FBQ3hELElBQUksQ0FBQyxTQUFTLEVBQUUsQ0FBQztZQUNmLE1BQU0sSUFBSSxLQUFLLENBQUMsZ0RBQWdELENBQUMsQ0FBQztRQUNwRSxDQUFDO1FBRUQsTUFBTSxLQUFLLEdBQUcsSUFBSSxNQUFNLENBQUMsS0FBSyxDQUFDLElBQUksRUFBRSxPQUFPLEVBQUU7WUFDNUMsU0FBUztZQUNULE9BQU8sRUFBRSxJQUFJLENBQUMsRUFBRSxDQUFDLGNBQWM7WUFDL0IsV0FBVyxFQUFFLE9BQU8sQ0FBQyxXQUFXO1lBQ2hDLCtCQUErQixFQUFFLE9BQU8sQ0FBQywrQkFBK0I7U0FDekUsQ0FBQyxDQUFDO1FBQ0YsSUFBaUMsQ0FBQyxLQUFLLEdBQUcsS0FBSyxDQUFDO1FBRWpELElBQUksT0FBTyxDQUFDLFVBQVUsRUFBRSxDQUFDO1lBQ3ZCLE1BQU0sZUFBZSxHQUFHLElBQUksVUFBVSxDQUFDLHFCQUFxQixDQUFDLElBQUksRUFBRSxpQkFBaUIsRUFBRTtnQkFDcEYsS0FBSztnQkFDTCxnQkFBZ0IsRUFBRSxtQkFBbUIsQ0FBQyxJQUFJLEVBQUUsT0FBTyxDQUFDLFVBQVUsQ0FBQztnQkFDL0QsTUFBTSxFQUFFLE9BQU8sQ0FBQyxVQUFVLENBQUMsTUFBTTtnQkFDakMsT0FBTyxFQUFFLE9BQU8sQ0FBQyxVQUFVLENBQUMsT0FBTztnQkFDbkMsUUFBUSxFQUFFLE9BQU8sQ0FBQyxVQUFVLENBQUMsUUFBUTtnQkFDckMsWUFBWSxFQUFFLE9BQU8sQ0FBQyxVQUFVLENBQUMsWUFBWTthQUM5QyxDQUFDLENBQUM7WUFDRixJQUErRCxDQUFDLGVBQWUsR0FBRyxlQUFlLENBQUM7UUFDckcsQ0FBQztJQUNILENBQUM7O0FBM0dILDhDQTRHQzs7O0FBRUQsU0FBUyxtQkFBbUIsQ0FBQyxLQUFnQixFQUFFLE9BQTJDO0lBQ3hGLE1BQU0sSUFBSSxHQUFHLE9BQU8sQ0FBQyxnQkFBZ0IsSUFBSSwrQkFBK0IsQ0FBQyxNQUFNLENBQUM7SUFDaEYsUUFBUSxJQUFJLEVBQUUsQ0FBQztRQUNiLEtBQUssK0JBQStCLENBQUMsV0FBVztZQUM5QyxPQUFPLFVBQVUsQ0FBQyxzQkFBc0IsQ0FBQyxXQUFXLENBQUM7UUFDdkQsS0FBSywrQkFBK0IsQ0FBQyxNQUFNO1lBQ3pDLE9BQU8sSUFBSSxVQUFVLENBQUMsc0JBQXNCLENBQUMsS0FBSyxFQUFFLHdCQUF3QixFQUFFO2dCQUM1RSxjQUFjLEVBQUUsVUFBVSxDQUFDLGNBQWMsQ0FBQyxlQUFlLENBQUM7b0JBQ3hELFVBQVUsRUFBRSxvQkFBb0IsQ0FBQyxPQUFPLENBQUMsVUFBVSxDQUFDO29CQUNwRCxRQUFRLEVBQUUsT0FBTyxDQUFDLFFBQVEsSUFBSSxzQkFBUSxDQUFDLE9BQU8sQ0FBQyxDQUFDLENBQUM7aUJBQ2xELENBQUM7YUFDSCxDQUFDLENBQUM7UUFDTCxLQUFLLCtCQUErQixDQUFDLE1BQU07WUFDekMsT0FBTyxJQUFJLFVBQVUsQ0FBQyxzQkFBc0IsQ0FBQyxLQUFLLEVBQUUsd0JBQXdCLEVBQUU7Z0JBQzVFLGNBQWMsRUFBRSxVQUFVLENBQUMsY0FBYyxDQUFDLGVBQWUsQ0FBQztvQkFDeEQsVUFBVSxFQUFFLG9CQUFvQixDQUFDLE9BQU8sQ0FBQyxVQUFVLENBQUM7b0JBQ3BELFFBQVEsRUFBRSxPQUFPLENBQUMsUUFBUSxJQUFJLHNCQUFRLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQztpQkFDbEQsQ0FBQzthQUNILENBQUMsQ0FBQztRQUNMO1lBQ0UsTUFBTSxJQUFJLEtBQUssQ0FBQyxrREFBa0QsTUFBTSxDQUFDLElBQUksQ0FBQyxFQUFFLENBQUMsQ0FBQztJQUN0RixDQUFDO0FBQ0gsQ0FBQztBQUVELFNBQVMsb0JBQW9CLENBQUMsS0FBYztJQUMxQyxNQUFNLEtBQUssR0FBRyxLQUFLLElBQUksRUFBRSxDQUFDO0lBQzFCLElBQUksQ0FBQyxNQUFNLENBQUMsUUFBUSxDQUFDLEtBQUssQ0FBQyxJQUFJLEtBQUssSUFBSSxDQUFDLElBQUksS0FBSyxJQUFJLEdBQUcsRUFBRSxDQUFDO1FBQzFELE1BQU0sSUFBSSxLQUFLLENBQUMsa0ZBQWtGLENBQUMsQ0FBQztJQUN0RyxDQUFDO0lBQ0QsT0FBTyxLQUFLLENBQUM7QUFDZixDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHsgRHVyYXRpb24gfSBmcm9tIFwiYXdzLWNkay1saWJcIjtcbmltcG9ydCAqIGFzIGNsb3Vkd2F0Y2ggZnJvbSBcImF3cy1jZGstbGliL2F3cy1jbG91ZHdhdGNoXCI7XG5pbXBvcnQgKiBhcyBjb2RlZGVwbG95IGZyb20gXCJhd3MtY2RrLWxpYi9hd3MtY29kZWRlcGxveVwiO1xuaW1wb3J0ICogYXMgaWFtIGZyb20gXCJhd3MtY2RrLWxpYi9hd3MtaWFtXCI7XG5pbXBvcnQgKiBhcyBsYW1iZGEgZnJvbSBcImF3cy1jZGstbGliL2F3cy1sYW1iZGFcIjtcbmltcG9ydCAqIGFzIGxvZ3MgZnJvbSBcImF3cy1jZGstbGliL2F3cy1sb2dzXCI7XG5pbXBvcnQgeyBDb25zdHJ1Y3QgfSBmcm9tIFwiY29uc3RydWN0c1wiO1xuXG4vKipcbiAqIFRyYWZmaWMgc2hpZnRpbmcgbW9kZSBmb3IgQXBwVGhlb3J5LW1hbmFnZWQgTGFtYmRhIGFsaWFzZXMuXG4gKi9cbmV4cG9ydCBlbnVtIEFwcFRoZW9yeUxhbWJkYVRyYWZmaWNTaGlmdFR5cGUge1xuICAvKipcbiAgICogU2hpZnQgYWxsIHRyYWZmaWMgdG8gdGhlIG5ldyB2ZXJzaW9uIGF0IG9uY2UuXG4gICAqL1xuICBBTExfQVRfT05DRSA9IFwiQUxMX0FUX09OQ0VcIixcblxuICAvKipcbiAgICogU2hpZnQgb25lIGNhbmFyeSBpbmNyZW1lbnQsIHdhaXQsIHRoZW4gc2hpZnQgdGhlIHJlbWFpbmluZyB0cmFmZmljLlxuICAgKi9cbiAgQ0FOQVJZID0gXCJDQU5BUllcIixcblxuICAvKipcbiAgICogU2hpZnQgdHJhZmZpYyBpbiBlcXVhbCBsaW5lYXIgaW5jcmVtZW50cy5cbiAgICovXG4gIExJTkVBUiA9IFwiTElORUFSXCIsXG59XG5cbi8qKlxuICogQ29kZURlcGxveSBkZXBsb3ltZW50IHByZWZlcmVuY2VzIGZvciBhbiBBcHBUaGVvcnkgTGFtYmRhIGFsaWFzLlxuICovXG5leHBvcnQgaW50ZXJmYWNlIEFwcFRoZW9yeUZ1bmN0aW9uRGVwbG95bWVudE9wdGlvbnMge1xuICAvKipcbiAgICogVHJhZmZpYyBzaGlmdGluZyBtb2RlLlxuICAgKiBAZGVmYXVsdCBBcHBUaGVvcnlMYW1iZGFUcmFmZmljU2hpZnRUeXBlLkNBTkFSWVxuICAgKi9cbiAgcmVhZG9ubHkgdHJhZmZpY1NoaWZ0VHlwZT86IEFwcFRoZW9yeUxhbWJkYVRyYWZmaWNTaGlmdFR5cGU7XG5cbiAgLyoqXG4gICAqIFBlcmNlbnRhZ2Ugc2hpZnRlZCBhdCBlYWNoIGNhbmFyeSBvciBsaW5lYXIgaW5jcmVtZW50LlxuICAgKiBAZGVmYXVsdCAxMFxuICAgKi9cbiAgcmVhZG9ubHkgcGVyY2VudGFnZT86IG51bWJlcjtcblxuICAvKipcbiAgICogVGltZSBiZXR3ZWVuIHRyYWZmaWMgc2hpZnRzLlxuICAgKiBAZGVmYXVsdCBEdXJhdGlvbi5taW51dGVzKDUpIGZvciBjYW5hcnksIER1cmF0aW9uLm1pbnV0ZXMoMSkgZm9yIGxpbmVhclxuICAgKi9cbiAgcmVhZG9ubHkgaW50ZXJ2YWw/OiBEdXJhdGlvbjtcblxuICAvKipcbiAgICogQ2xvdWRXYXRjaCBhbGFybXMgdGhhdCBzdG9wIGFuZCByb2xsIGJhY2sgZGVwbG95bWVudHMuXG4gICAqIEBkZWZhdWx0IFtdXG4gICAqL1xuICByZWFkb25seSBhbGFybXM/OiBjbG91ZHdhdGNoLklBbGFybVtdO1xuXG4gIC8qKlxuICAgKiBMYW1iZGEgcHJlLXRyYWZmaWMgaG9vay5cbiAgICogQGRlZmF1bHQgdW5kZWZpbmVkXG4gICAqL1xuICByZWFkb25seSBwcmVIb29rPzogbGFtYmRhLklGdW5jdGlvbjtcblxuICAvKipcbiAgICogTGFtYmRhIHBvc3QtdHJhZmZpYyBob29rLlxuICAgKiBAZGVmYXVsdCB1bmRlZmluZWRcbiAgICovXG4gIHJlYWRvbmx5IHBvc3RIb29rPzogbGFtYmRhLklGdW5jdGlvbjtcblxuICAvKipcbiAgICogQ29kZURlcGxveSBhdXRvLXJvbGxiYWNrIGNvbmZpZ3VyYXRpb24uXG4gICAqIEBkZWZhdWx0IENvZGVEZXBsb3kgZGVmYXVsdHNcbiAgICovXG4gIHJlYWRvbmx5IGF1dG9Sb2xsYmFjaz86IGNvZGVkZXBsb3kuQXV0b1JvbGxiYWNrQ29uZmlnO1xufVxuXG4vKipcbiAqIEFsaWFzIGFuZCBwcm92aXNpb25lZC1jb25jdXJyZW5jeSBvcHRpb25zIGZvciBhbiBBcHBUaGVvcnkgZnVuY3Rpb24uXG4gKi9cbmV4cG9ydCBpbnRlcmZhY2UgQXBwVGhlb3J5RnVuY3Rpb25BbGlhc09wdGlvbnMge1xuICAvKipcbiAgICogTGFtYmRhIGFsaWFzIG5hbWUuXG4gICAqIEBkZWZhdWx0IFwibGl2ZVwiXG4gICAqL1xuICByZWFkb25seSBuYW1lPzogc3RyaW5nO1xuXG4gIC8qKlxuICAgKiBBbGlhcyBkZXNjcmlwdGlvbi5cbiAgICogQGRlZmF1bHQgdW5kZWZpbmVkXG4gICAqL1xuICByZWFkb25seSBkZXNjcmlwdGlvbj86IHN0cmluZztcblxuICAvKipcbiAgICogUHJvdmlzaW9uZWQgY29uY3VycmVuY3kgY29uZmlndXJlZCBvbiB0aGUgYWxpYXMuXG4gICAqIEBkZWZhdWx0IHVuZGVmaW5lZFxuICAgKi9cbiAgcmVhZG9ubHkgcHJvdmlzaW9uZWRDb25jdXJyZW50RXhlY3V0aW9ucz86IG51bWJlcjtcblxuICAvKipcbiAgICogT3B0aW9uYWwgQ29kZURlcGxveSB0cmFmZmljIHNoaWZ0aW5nIGZvciB0aGlzIGFsaWFzLlxuICAgKiBAZGVmYXVsdCB1bmRlZmluZWRcbiAgICovXG4gIHJlYWRvbmx5IGRlcGxveW1lbnQ/OiBBcHBUaGVvcnlGdW5jdGlvbkRlcGxveW1lbnRPcHRpb25zO1xufVxuXG5leHBvcnQgaW50ZXJmYWNlIEFwcFRoZW9yeUZ1bmN0aW9uUHJvcHMgZXh0ZW5kcyBsYW1iZGEuRnVuY3Rpb25Qcm9wcyB7XG4gIC8qKlxuICAgKiBTdGFibGUgcGh5c2ljYWwgbmFtZSBmb3IgdGhlIEFwcFRoZW9yeS1tYW5hZ2VkIExhbWJkYSBleGVjdXRpb24gcm9sZS5cbiAgICpcbiAgICogQXBwVGhlb3J5IHJlbmFtZXMgdGhlIHJvbGUgY3JlYXRlZCBieSB0aGUgTGFtYmRhIEwyIHNvIGFsbCBDREstY29tcHV0ZWRcbiAgICogbWFuYWdlZCBwb2xpY2llcyBhcmUgcHJlc2VydmVkLCBhbmQgZmFpbHMgc3ludGhlc2lzIGlmIHRoZSByZXF1ZXN0ZWQgbmFtZVxuICAgKiBjYW5ub3QgYmUgYXBwbGllZCBleGFjdGx5LiBEbyBub3QgY29tYmluZSB0aGlzIHdpdGggdGhlIGluaGVyaXRlZCBgcm9sZWBcbiAgICogcHJvcDsgY2FsbGVyLXByb3ZpZGVkIHJvbGVzIG93biB0aGVpciBwaHlzaWNhbCBuYW1lLlxuICAgKlxuICAgKiBAZGVmYXVsdCB1bmRlZmluZWRcbiAgICovXG4gIHJlYWRvbmx5IHJvbGVOYW1lPzogc3RyaW5nO1xuXG4gIC8qKlxuICAgKiBPcHRpb25hbCBBcHBUaGVvcnktbWFuYWdlZCBMYW1iZGEgYWxpYXMuXG4gICAqXG4gICAqIFdoZW4gc2V0LCB0aGUgYWxpYXMgcG9pbnRzIGF0IHRoZSBmdW5jdGlvbidzIGN1cnJlbnQgdmVyc2lvbiBhbmQgY2FuIGFsc29cbiAgICogY2FycnkgcHJvdmlzaW9uZWQgY29uY3VycmVuY3kgYW5kIENvZGVEZXBsb3kgdHJhZmZpYyBzaGlmdGluZy5cbiAgICpcbiAgICogQGRlZmF1bHQgdW5kZWZpbmVkXG4gICAqL1xuICByZWFkb25seSBhbGlhcz86IEFwcFRoZW9yeUZ1bmN0aW9uQWxpYXNPcHRpb25zO1xufVxuXG5leHBvcnQgY2xhc3MgQXBwVGhlb3J5RnVuY3Rpb24gZXh0ZW5kcyBDb25zdHJ1Y3Qge1xuICBwdWJsaWMgcmVhZG9ubHkgZm46IGxhbWJkYS5GdW5jdGlvbjtcbiAgcHVibGljIHJlYWRvbmx5IGxvZ0dyb3VwPzogbG9ncy5JTG9nR3JvdXBSZWY7XG4gIHB1YmxpYyByZWFkb25seSBhbGlhcz86IGxhbWJkYS5BbGlhcztcbiAgcHVibGljIHJlYWRvbmx5IGRlcGxveW1lbnRHcm91cD86IGNvZGVkZXBsb3kuTGFtYmRhRGVwbG95bWVudEdyb3VwO1xuXG4gIGNvbnN0cnVjdG9yKHNjb3BlOiBDb25zdHJ1Y3QsIGlkOiBzdHJpbmcsIHByb3BzOiBBcHBUaGVvcnlGdW5jdGlvblByb3BzKSB7XG4gICAgc3VwZXIoc2NvcGUsIGlkKTtcblxuICAgIGNvbnN0IHsgYWxpYXMsIHJvbGVOYW1lLCAuLi5pbnB1dExhbWJkYVByb3BzIH0gPSBwcm9wcztcbiAgICBjb25zdCBsYW1iZGFQcm9wczogbGFtYmRhLkZ1bmN0aW9uUHJvcHMgPSB7IC4uLmlucHV0TGFtYmRhUHJvcHMgfTtcbiAgICBpZiAocm9sZU5hbWUgIT09IHVuZGVmaW5lZCkge1xuICAgICAgaWYgKGxhbWJkYVByb3BzLnJvbGUpIHtcbiAgICAgICAgdGhyb3cgbmV3IEVycm9yKFxuICAgICAgICAgIFwiQXBwVGhlb3J5RnVuY3Rpb24gY2Fubm90IGhvbm9yIHByb3BzLnJvbGVOYW1lIHdoZW4gcHJvcHMucm9sZSBzdXBwbGllcyB0aGUgZXhlY3V0aW9uIHJvbGU7IG9taXQgcHJvcHMucm9sZSBvciBjb25maWd1cmUgaXRzIG5hbWUgd2hlcmUgdGhhdCByb2xlIGlzIGNyZWF0ZWRcIixcbiAgICAgICAgKTtcbiAgICAgIH1cbiAgICB9XG4gICAgY29uc3QgbG9nUmV0ZW50aW9uID0gbGFtYmRhUHJvcHMubG9nUmV0ZW50aW9uID8/IGxvZ3MuUmV0ZW50aW9uRGF5cy5PTkVfTU9OVEg7XG4gICAgY29uc3QgbG9nUmVtb3ZhbFBvbGljeSA9IGxhbWJkYVByb3BzLmxvZ1JlbW92YWxQb2xpY3k7XG4gICAgZGVsZXRlIChsYW1iZGFQcm9wcyBhcyB7IGxvZ1JldGVudGlvbj86IGxvZ3MuUmV0ZW50aW9uRGF5cyB9KS5sb2dSZXRlbnRpb247XG4gICAgZGVsZXRlIChsYW1iZGFQcm9wcyBhcyB7IGxvZ1JlbW92YWxQb2xpY3k/OiB1bmtub3duIH0pLmxvZ1JlbW92YWxQb2xpY3k7XG4gICAgZGVsZXRlIChsYW1iZGFQcm9wcyBhcyB7IGxvZ1JldGVudGlvblJldHJ5T3B0aW9ucz86IHVua25vd24gfSkubG9nUmV0ZW50aW9uUmV0cnlPcHRpb25zO1xuICAgIGRlbGV0ZSAobGFtYmRhUHJvcHMgYXMgeyBsb2dSZXRlbnRpb25Sb2xlPzogdW5rbm93biB9KS5sb2dSZXRlbnRpb25Sb2xlO1xuXG4gICAgbGV0IGJvdW5kTG9nR3JvdXAgPSBsYW1iZGFQcm9wcy5sb2dHcm91cDtcbiAgICBpZiAoIWJvdW5kTG9nR3JvdXAgJiYgbGFtYmRhUHJvcHMuZnVuY3Rpb25OYW1lKSB7XG4gICAgICBib3VuZExvZ0dyb3VwID0gbmV3IGxvZ3MuTG9nR3JvdXAodGhpcywgXCJMb2dHcm91cFwiLCB7XG4gICAgICAgIGxvZ0dyb3VwTmFtZTogYC9hd3MvbGFtYmRhLyR7bGFtYmRhUHJvcHMuZnVuY3Rpb25OYW1lfWAsXG4gICAgICAgIHJldGVudGlvbjogbG9nUmV0ZW50aW9uLFxuICAgICAgICByZW1vdmFsUG9saWN5OiBsb2dSZW1vdmFsUG9saWN5LFxuICAgICAgfSk7XG4gICAgfVxuXG4gICAgdGhpcy5mbiA9IG5ldyBsYW1iZGEuRnVuY3Rpb24odGhpcywgXCJGdW5jdGlvblwiLCB7XG4gICAgICAuLi5sYW1iZGFQcm9wcyxcbiAgICAgIGxvZ0dyb3VwOiBib3VuZExvZ0dyb3VwLFxuICAgICAgYXJjaGl0ZWN0dXJlOiBsYW1iZGFQcm9wcy5hcmNoaXRlY3R1cmUgPz8gbGFtYmRhLkFyY2hpdGVjdHVyZS5BUk1fNjQsXG4gICAgICB0cmFjaW5nOiBsYW1iZGFQcm9wcy50cmFjaW5nID8/IGxhbWJkYS5UcmFjaW5nLkFDVElWRSxcbiAgICAgIG1lbW9yeVNpemU6IGxhbWJkYVByb3BzLm1lbW9yeVNpemUgPz8gMjU2LFxuICAgICAgdGltZW91dDogbGFtYmRhUHJvcHMudGltZW91dCA/PyBEdXJhdGlvbi5zZWNvbmRzKDEwKSxcbiAgICB9KTtcblxuICAgIGlmIChyb2xlTmFtZSAhPT0gdW5kZWZpbmVkKSB7XG4gICAgICBpZiAoIXJvbGVOYW1lLnRyaW0oKSkge1xuICAgICAgICB0aHJvdyBuZXcgRXJyb3IoXCJBcHBUaGVvcnlGdW5jdGlvbiByb2xlTmFtZSBtdXN0IG5vdCBiZSBlbXB0eVwiKTtcbiAgICAgIH1cbiAgICAgIGlmIChyb2xlTmFtZS5sZW5ndGggPiA2NCkge1xuICAgICAgICB0aHJvdyBuZXcgRXJyb3IoXCJBcHBUaGVvcnlGdW5jdGlvbiByb2xlTmFtZSBtdXN0IG5vdCBleGNlZWQgNjQgY2hhcmFjdGVyc1wiKTtcbiAgICAgIH1cbiAgICAgIGlmICghL15bXFx3Kz0sLkAtXSskLy50ZXN0KHJvbGVOYW1lKSkge1xuICAgICAgICB0aHJvdyBuZXcgRXJyb3IoXCJBcHBUaGVvcnlGdW5jdGlvbiByb2xlTmFtZSBtdXN0IG1hdGNoIFtcXFxcdys9LC5ALV0rXCIpO1xuICAgICAgfVxuICAgICAgY29uc3Qgcm9sZVJlc291cmNlID0gdGhpcy5mbi5yb2xlPy5ub2RlLmRlZmF1bHRDaGlsZDtcbiAgICAgIGlmICghKHJvbGVSZXNvdXJjZSBpbnN0YW5jZW9mIGlhbS5DZm5Sb2xlKSkge1xuICAgICAgICB0aHJvdyBuZXcgRXJyb3IoXG4gICAgICAgICAgYEFwcFRoZW9yeUZ1bmN0aW9uIGNhbm5vdCBhcHBseSB0aGUgcmVxdWlyZWQgc3RhYmxlIHJvbGVOYW1lICR7SlNPTi5zdHJpbmdpZnkocm9sZU5hbWUpfSBiZWNhdXNlIHRoZSBMYW1iZGEgZXhlY3V0aW9uIHJvbGUncyBkZWZhdWx0IGNoaWxkIGlzIG5vdCBhbiBBV1M6OklBTTo6Um9sZWAsXG4gICAgICAgICk7XG4gICAgICB9XG4gICAgICByb2xlUmVzb3VyY2UuYWRkUHJvcGVydHlPdmVycmlkZShcIlJvbGVOYW1lXCIsIHJvbGVOYW1lKTtcbiAgICB9XG5cbiAgICBpZiAoYm91bmRMb2dHcm91cCkge1xuICAgICAgKHRoaXMgYXMgeyBsb2dHcm91cD86IGxvZ3MuSUxvZ0dyb3VwUmVmIH0pLmxvZ0dyb3VwID0gYm91bmRMb2dHcm91cDtcbiAgICB9IGVsc2Uge1xuICAgICAgLy8gQW5vbnltb3VzIExhbWJkYSBwaHlzaWNhbCBuYW1lcyBhcmUgZ2VuZXJhdGVkIGJ5IENsb3VkRm9ybWF0aW9uLiBLZWVwXG4gICAgICAvLyB0aGUgZmluaXRlLXJldGVudGlvbiBsb2cgZ3JvdXAsIGJ1dCByZXF1aXJlIGNhbGxlcnMgdGhhdCBuZWVkIGFcbiAgICAgIC8vIGZhaWwtc2FmZSBleGlzdGluZy1zdGFjayB1cGdyYWRlL2Fkb3B0aW9uIHBhdGggdG8gcGFzcyBsb2dHcm91cCBvciBhXG4gICAgICAvLyBjb25jcmV0ZSBmdW5jdGlvbk5hbWUgc28gdGhlIExhbWJkYSBMMiBjYW4gYmluZCB0aGUgZ3JvdXAgdXAgZnJvbnQuXG4gICAgICBjb25zdCBsb2dHcm91cCA9IG5ldyBsb2dzLkxvZ0dyb3VwKHRoaXMsIFwiTG9nR3JvdXBcIiwge1xuICAgICAgICBsb2dHcm91cE5hbWU6IGAvYXdzL2xhbWJkYS8ke3RoaXMuZm4uZnVuY3Rpb25OYW1lfWAsXG4gICAgICAgIHJldGVudGlvbjogbG9nUmV0ZW50aW9uLFxuICAgICAgICByZW1vdmFsUG9saWN5OiBsb2dSZW1vdmFsUG9saWN5LFxuICAgICAgfSk7XG4gICAgICAodGhpcyBhcyB7IGxvZ0dyb3VwPzogbG9ncy5JTG9nR3JvdXBSZWYgfSkubG9nR3JvdXAgPSBsb2dHcm91cDtcbiAgICB9XG5cbiAgICBpZiAoYWxpYXMpIHtcbiAgICAgIHRoaXMuY29uZmlndXJlQWxpYXMoYWxpYXMpO1xuICAgIH1cbiAgfVxuXG4gIHByaXZhdGUgY29uZmlndXJlQWxpYXMob3B0aW9uczogQXBwVGhlb3J5RnVuY3Rpb25BbGlhc09wdGlvbnMpOiB2b2lkIHtcbiAgICBjb25zdCBhbGlhc05hbWUgPSBTdHJpbmcob3B0aW9ucy5uYW1lID8/IFwibGl2ZVwiKS50cmltKCk7XG4gICAgaWYgKCFhbGlhc05hbWUpIHtcbiAgICAgIHRocm93IG5ldyBFcnJvcihcIkFwcFRoZW9yeUZ1bmN0aW9uIGFsaWFzLm5hbWUgbXVzdCBub3QgYmUgZW1wdHlcIik7XG4gICAgfVxuXG4gICAgY29uc3QgYWxpYXMgPSBuZXcgbGFtYmRhLkFsaWFzKHRoaXMsIFwiQWxpYXNcIiwge1xuICAgICAgYWxpYXNOYW1lLFxuICAgICAgdmVyc2lvbjogdGhpcy5mbi5jdXJyZW50VmVyc2lvbixcbiAgICAgIGRlc2NyaXB0aW9uOiBvcHRpb25zLmRlc2NyaXB0aW9uLFxuICAgICAgcHJvdmlzaW9uZWRDb25jdXJyZW50RXhlY3V0aW9uczogb3B0aW9ucy5wcm92aXNpb25lZENvbmN1cnJlbnRFeGVjdXRpb25zLFxuICAgIH0pO1xuICAgICh0aGlzIGFzIHsgYWxpYXM/OiBsYW1iZGEuQWxpYXMgfSkuYWxpYXMgPSBhbGlhcztcblxuICAgIGlmIChvcHRpb25zLmRlcGxveW1lbnQpIHtcbiAgICAgIGNvbnN0IGRlcGxveW1lbnRHcm91cCA9IG5ldyBjb2RlZGVwbG95LkxhbWJkYURlcGxveW1lbnRHcm91cCh0aGlzLCBcIkRlcGxveW1lbnRHcm91cFwiLCB7XG4gICAgICAgIGFsaWFzLFxuICAgICAgICBkZXBsb3ltZW50Q29uZmlnOiBkZXBsb3ltZW50Q29uZmlnRm9yKHRoaXMsIG9wdGlvbnMuZGVwbG95bWVudCksXG4gICAgICAgIGFsYXJtczogb3B0aW9ucy5kZXBsb3ltZW50LmFsYXJtcyxcbiAgICAgICAgcHJlSG9vazogb3B0aW9ucy5kZXBsb3ltZW50LnByZUhvb2ssXG4gICAgICAgIHBvc3RIb29rOiBvcHRpb25zLmRlcGxveW1lbnQucG9zdEhvb2ssXG4gICAgICAgIGF1dG9Sb2xsYmFjazogb3B0aW9ucy5kZXBsb3ltZW50LmF1dG9Sb2xsYmFjayxcbiAgICAgIH0pO1xuICAgICAgKHRoaXMgYXMgeyBkZXBsb3ltZW50R3JvdXA/OiBjb2RlZGVwbG95LkxhbWJkYURlcGxveW1lbnRHcm91cCB9KS5kZXBsb3ltZW50R3JvdXAgPSBkZXBsb3ltZW50R3JvdXA7XG4gICAgfVxuICB9XG59XG5cbmZ1bmN0aW9uIGRlcGxveW1lbnRDb25maWdGb3Ioc2NvcGU6IENvbnN0cnVjdCwgb3B0aW9uczogQXBwVGhlb3J5RnVuY3Rpb25EZXBsb3ltZW50T3B0aW9ucyk6IGNvZGVkZXBsb3kuSUxhbWJkYURlcGxveW1lbnRDb25maWcge1xuICBjb25zdCB0eXBlID0gb3B0aW9ucy50cmFmZmljU2hpZnRUeXBlID8/IEFwcFRoZW9yeUxhbWJkYVRyYWZmaWNTaGlmdFR5cGUuQ0FOQVJZO1xuICBzd2l0Y2ggKHR5cGUpIHtcbiAgICBjYXNlIEFwcFRoZW9yeUxhbWJkYVRyYWZmaWNTaGlmdFR5cGUuQUxMX0FUX09OQ0U6XG4gICAgICByZXR1cm4gY29kZWRlcGxveS5MYW1iZGFEZXBsb3ltZW50Q29uZmlnLkFMTF9BVF9PTkNFO1xuICAgIGNhc2UgQXBwVGhlb3J5TGFtYmRhVHJhZmZpY1NoaWZ0VHlwZS5MSU5FQVI6XG4gICAgICByZXR1cm4gbmV3IGNvZGVkZXBsb3kuTGFtYmRhRGVwbG95bWVudENvbmZpZyhzY29wZSwgXCJMaW5lYXJEZXBsb3ltZW50Q29uZmlnXCIsIHtcbiAgICAgICAgdHJhZmZpY1JvdXRpbmc6IGNvZGVkZXBsb3kuVHJhZmZpY1JvdXRpbmcudGltZUJhc2VkTGluZWFyKHtcbiAgICAgICAgICBwZXJjZW50YWdlOiBub3JtYWxpemVkUGVyY2VudGFnZShvcHRpb25zLnBlcmNlbnRhZ2UpLFxuICAgICAgICAgIGludGVydmFsOiBvcHRpb25zLmludGVydmFsID8/IER1cmF0aW9uLm1pbnV0ZXMoMSksXG4gICAgICAgIH0pLFxuICAgICAgfSk7XG4gICAgY2FzZSBBcHBUaGVvcnlMYW1iZGFUcmFmZmljU2hpZnRUeXBlLkNBTkFSWTpcbiAgICAgIHJldHVybiBuZXcgY29kZWRlcGxveS5MYW1iZGFEZXBsb3ltZW50Q29uZmlnKHNjb3BlLCBcIkNhbmFyeURlcGxveW1lbnRDb25maWdcIiwge1xuICAgICAgICB0cmFmZmljUm91dGluZzogY29kZWRlcGxveS5UcmFmZmljUm91dGluZy50aW1lQmFzZWRDYW5hcnkoe1xuICAgICAgICAgIHBlcmNlbnRhZ2U6IG5vcm1hbGl6ZWRQZXJjZW50YWdlKG9wdGlvbnMucGVyY2VudGFnZSksXG4gICAgICAgICAgaW50ZXJ2YWw6IG9wdGlvbnMuaW50ZXJ2YWwgPz8gRHVyYXRpb24ubWludXRlcyg1KSxcbiAgICAgICAgfSksXG4gICAgICB9KTtcbiAgICBkZWZhdWx0OlxuICAgICAgdGhyb3cgbmV3IEVycm9yKGBBcHBUaGVvcnlGdW5jdGlvbiB1bnN1cHBvcnRlZCBkZXBsb3ltZW50IHR5cGU6ICR7U3RyaW5nKHR5cGUpfWApO1xuICB9XG59XG5cbmZ1bmN0aW9uIG5vcm1hbGl6ZWRQZXJjZW50YWdlKGlucHV0PzogbnVtYmVyKTogbnVtYmVyIHtcbiAgY29uc3QgdmFsdWUgPSBpbnB1dCA/PyAxMDtcbiAgaWYgKCFOdW1iZXIuaXNGaW5pdGUodmFsdWUpIHx8IHZhbHVlIDw9IDAgfHwgdmFsdWUgPj0gMTAwKSB7XG4gICAgdGhyb3cgbmV3IEVycm9yKFwiQXBwVGhlb3J5RnVuY3Rpb24gZGVwbG95bWVudCBwZXJjZW50YWdlIG11c3QgYmUgZ3JlYXRlciB0aGFuIDAgYW5kIGxlc3MgdGhhbiAxMDBcIik7XG4gIH1cbiAgcmV0dXJuIHZhbHVlO1xufVxuIl19