#!/usr/bin/env bash
# Purpose: regenerate the cdk/README.md construct inventory from cdk/lib/index.ts exports.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

mode="update"
if [[ "${1:-}" == "--check" ]]; then
  mode="check"
elif [[ "${1:-}" != "" ]]; then
  echo "cdk-readme-inventory: FAIL (usage: $0 [--check])" >&2
  exit 1
fi

python3 - "${mode}" <<'PY'
from __future__ import annotations

import re
import sys
from pathlib import Path

mode = sys.argv[1]
root = Path.cwd()
readme_path = root / "cdk" / "README.md"
index_path = root / "cdk" / "lib" / "index.ts"
start = "<!-- apptheory-cdk-inventory:start -->"
end = "<!-- apptheory-cdk-inventory:end -->"

exports: list[tuple[str, str]] = []
for raw in index_path.read_text(encoding="utf-8").splitlines():
    match = re.match(r'^export \* from "(?P<module>\./[A-Za-z0-9_-]+)";\s*$', raw.strip())
    if not match:
        continue
    module = match.group("module")
    module_path = root / "cdk" / "lib" / f"{module[2:]}.ts"
    if not module_path.exists():
        raise SystemExit(f"cdk-readme-inventory: FAIL (missing {module_path.relative_to(root)})")
    source = module_path.read_text(encoding="utf-8")
    for class_name in re.findall(r"^export class (AppTheory[A-Za-z0-9_]*)\b", source, flags=re.MULTILINE):
        exports.append((class_name, str(module_path.relative_to(root))))

if not exports:
    raise SystemExit("cdk-readme-inventory: FAIL (no AppTheory construct classes found from cdk/lib/index.ts)")

seen: set[str] = set()
duplicates: list[str] = []
for class_name, _ in exports:
    if class_name in seen:
        duplicates.append(class_name)
    seen.add(class_name)
if duplicates:
    raise SystemExit(f"cdk-readme-inventory: FAIL (duplicate construct exports: {', '.join(sorted(duplicates))})")

lines = [
    start,
    "<!-- Generated by scripts/update-cdk-readme-inventory.sh; do not edit this block by hand. -->",
]
lines.extend(f"- `{class_name}` — exported from `{module_path}`." for class_name, module_path in exports)
lines.append(end)
block = "\n".join(lines)

readme = readme_path.read_text(encoding="utf-8")
if start in readme or end in readme:
    if start not in readme or end not in readme or readme.index(start) > readme.index(end):
        raise SystemExit("cdk-readme-inventory: FAIL (malformed inventory markers in cdk/README.md)")
    before = readme[: readme.index(start)]
    after = readme[readme.index(end) + len(end) :]
    updated = before + block + after
else:
    constructs_heading = "## Constructs\n"
    next_heading = "## Minimal example"
    if constructs_heading not in readme or next_heading not in readme:
        raise SystemExit("cdk-readme-inventory: FAIL (could not locate Constructs section in cdk/README.md)")
    before = readme[: readme.index(constructs_heading) + len(constructs_heading)]
    after = readme[readme.index(next_heading) :]
    intro = (
        "\nThe inventory below is generated from `cdk/lib/index.ts` exports. "
        "Run `./scripts/update-cdk-readme-inventory.sh` after adding or removing a construct export.\n\n"
    )
    updated = before + intro + block + "\n\n" + after

if mode == "check":
    if updated != readme:
        raise SystemExit(
            "cdk-readme-inventory: FAIL (cdk/README.md inventory is stale; "
            "run ./scripts/update-cdk-readme-inventory.sh and commit the diff)"
        )
    print(f"cdk-readme-inventory: PASS ({len(exports)} constructs)")
else:
    readme_path.write_text(updated, encoding="utf-8")
    print(f"cdk-readme-inventory: updated ({len(exports)} constructs)")
PY
