#!/usr/bin/env python3

from __future__ import annotations

import ast
import hashlib
import sys
from pathlib import Path


def sha256_hex(data: bytes) -> str:
    h = hashlib.sha256()
    h.update(data)
    return h.hexdigest()


def extract_all_names(module: ast.Module) -> list[str]:
    assignments: list[ast.Assign] = [
        n
        for n in module.body
        if isinstance(n, ast.Assign)
        and len(n.targets) == 1
        and isinstance(n.targets[0], ast.Name)
        and n.targets[0].id == "__all__"
    ]
    if not assignments:
        raise ValueError("missing __all__ assignment")

    value = assignments[-1].value
    if not isinstance(value, (ast.List, ast.Tuple)):
        raise ValueError("__all__ must be a list or tuple literal")

    names: list[str] = []
    for elt in value.elts:
        if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
            names.append(elt.value)
            continue
        if isinstance(elt, ast.Str):
            names.append(elt.s)
            continue
        raise ValueError(f"__all__ must contain only strings; found {type(elt).__name__}")

    names.sort()
    return names


def main() -> int:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "py/src/apptheory/__init__.py")
    data = src.read_bytes()
    text = data.decode("utf-8")
    module = ast.parse(text, filename=src.as_posix())

    names = extract_all_names(module)

    sys.stdout.write("# AppTheory Python public API snapshot\n")
    sys.stdout.write(f"# Source: {src.as_posix()}\n")
    sys.stdout.write(f"# SHA256: {sha256_hex(data)}\n")
    sys.stdout.write("# Generated by: scripts/update-api-snapshots.sh\n")
    sys.stdout.write("# DO NOT EDIT MANUALLY\n\n")

    sys.stdout.write("[__all__]\n")
    for name in names:
        sys.stdout.write(f"{name}\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

