#!/usr/bin/env python3

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


EXPORT_DECL_RE = re.compile(
    r"^\s*export\s+(?:declare\s+)?(interface|class|function|type|const|let|var|enum|namespace)\s+([A-Za-z0-9_]+)\b"
)
EXPORT_LIST_RE = re.compile(r"^\s*export\s*\{([^}]*)\}\s*(?:from\s+['\"][^'\"]+['\"])?\s*;?\s*$")
EXPORT_STAR_RE = re.compile(r"^\s*export\s+\*\s+from\s+['\"][^'\"]+['\"]\s*;?\s*$")


def sha256_hex(data: bytes) -> str:
    h = hashlib.sha256()
    h.update(data)
    return h.hexdigest()


def parse_exports(text: str) -> tuple[list[tuple[str, str]], list[str]]:
    exports: list[tuple[str, str]] = []
    passthrough: list[str] = []

    for line in text.splitlines():
        m = EXPORT_DECL_RE.match(line)
        if m:
            kind = m.group(1)
            name = m.group(2)
            exports.append((name, kind))
            continue

        m = EXPORT_LIST_RE.match(line)
        if m:
            raw = m.group(1).strip()
            if not raw:
                continue
            for part in raw.split(","):
                part = part.strip()
                if not part:
                    continue
                # `Foo as Bar` or just `Foo`
                if " as " in part:
                    _, alias = part.split(" as ", 1)
                    name = alias.strip()
                else:
                    name = part
                exports.append((name, "re-export"))
            continue

        if EXPORT_STAR_RE.match(line):
            passthrough.append(line.strip())

    exports.sort(key=lambda x: (x[0], x[1]))
    passthrough.sort()
    return exports, passthrough


def main() -> int:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "ts/dist/index.d.ts")
    data = src.read_bytes()
    text = data.decode("utf-8")

    exports, passthrough = parse_exports(text)

    sys.stdout.write("# AppTheory TypeScript public API snapshot\n")
    sys.stdout.write(f"# Source: {src.as_posix()}\n")
    sys.stdout.write(f"# SHA256: {sha256_hex(data)}\n")
    sys.stdout.write("# Generated by: scripts/update-api-snapshots.sh\n")
    sys.stdout.write("# DO NOT EDIT MANUALLY\n\n")

    sys.stdout.write("[exports]\n")
    for name, kind in exports:
        sys.stdout.write(f"{name}\t{kind}\n")

    if passthrough:
        sys.stdout.write("\n[export-statements]\n")
        for stmt in passthrough:
            sys.stdout.write(f"{stmt}\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

